/*
 * device_conf.h
 *
 *  Created on: 2018/07/03
 *      Author: Keshikan
 */

#ifndef DEVICE_CONF_H_
#define DEVICE_CONF_H_

#define LED_POW_GPIO GPIOA
#define LED_POW_PIN GPIO_PIN_15
#define LED_POW_CLK_ENABLE __HAL_RCC_GPIOA_CLK_ENABLE

#define LED_FAULT_GPIO GPIOA
#define LED_FAULT_PIN GPIO_PIN_10
#define LED_FAULT_CLK_ENABLE __HAL_RCC_GPIOA_CLK_ENABLE

#define BUTTON_GPIO GPIOA
#define BUTTON_PIN GPIO_PIN_7
#define BUTTON_CLK_ENABLE __HAL_RCC_GPIOA_CLK_ENABLE

#define PWM_AUDIO_GPIO GPIOB
#define PWM_AUDIO_PIN GPIO_PIN_3
#define PWM_AUDIO_CLK_ENABLE __HAL_RCC_GPIOB_CLK_ENABLE

#define BOOST_GPIO GPIOA
#define BOOST_PIN GPIO_PIN_8
#define BOOST_CLK_ENABLE __HAL_RCC_GPIOA_CLK_ENABLE

#define I_OUT_GPIO GPIOA
#define I_OUT_PIN GPIO_PIN_0
#define I_OUT_CLK_ENABLE __HAL_RCC_GPIOA_CLK_ENABLE

#define U_OUT_GPIO GPIOA
#define U_OUT_PIN GPIO_PIN_1
#define U_OUT_CLK_ENABLE __HAL_RCC_GPIOA_CLK_ENABLE

#define U_USB_GPIO GPIOA
#define U_USB_PIN GPIO_PIN_2
#define U_USB_CLK_ENABLE __HAL_RCC_GPIOA_CLK_ENABLE

#endif /* DEVICE_CONF_H_ */
